<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\core.Application\core.Application.csproj" />
	</ItemGroup>

	<ItemGroup>

		<FrameworkReference Include="Microsoft.AspNetCore.App" />

		<PackageReference Include="BCrypt.Net-Next" />

		<PackageReference Include="Google.Apis.Auth" />

		<PackageReference Include="Microsoft.IdentityModel.Tokens" />

		<PackageReference Include="System.IdentityModel.Tokens.Jwt" />

	</ItemGroup>

</Project>